server:
  port: 8080
spring:
  application:
    name: springboot-junit-mockito-demo
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 000000
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource